[tool.poetry]
name = "shell_scripts"
version = "0.1.0"
description = ""
authors = ["Joe Kaufeld <joe@grafeas.org>"]

[tool.poetry.dependencies]
python = "^3.8"
crayons = "^0.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
